
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: demo_app_development
test:
  <<: *default
  database: demo_app_test
  
production:
  <<: *default
  database: demo_app_production
  username: demo_app
  password: <%= ENV['DEMO_APP_DATABASE_PASSWORD'] %>
